apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ox3xcd1r4-nodejs
  janus-idp.io/tekton: ox3xcd1r4-nodejs
  backstage.io/kubernetes-id: ox3xcd1r4-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ox3xcd1r4-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
